### ISSUE TITLE
[BUG] Ambiguous occurrence names in list-occurrences

### ISSUE THREAD

**Issue by ml019** [hamlet-io/executor-python#197]
## Current Behaviour
If a solution has subcomponents with identical ids (but different names) , ` hamlet component list-occurrences` shows the same name for all of the subcomponent occurrences.

## Expected Behaviour
Names need to be unique to individually identify these subcomponents when using `hamlet component describe-occurrence`

## Possible Solution
Detect duplicate names and add the component type to the end of the name.

## Steps to Reproduce

1. Define two subcomponents of the same component with identical names
2. Run `hamlet component list-occurrences`
3.
4.

## Your Environment
* hamlet, version 9.0.2

**Comment by roleyfoley** [comment]
I tested this as part of https://github.com/hamlet-io/engine/issues/1726 and it looks like this is what the executor receives from the occurrences entrance provided by the engine. So I don't think is is an issue in the executor and is actually what is provided by the occurrences entrance in https://github.com/hamlet-io/engine

**Comment by ml019** [comment]
@roleyfoley what value is the cli using for the `Name` column?  The `TypedName` attribute in Core includes the type so would meet the requirement but the need to use it is not something the occurrence builder code is aware of. It is more of a usability thing in the cli IMHO.

Maybe we switch to the TypedName in the cli? The user can cut/paste the value so a couple of extra letters aren't going to hurt.

**Comment by ml019** [comment]
@roleyfoley just added `TypedRawName` to the occurrence structure. Thinking we use this instead of `RawName` in `list-occurrences` and `describe-occurrences`

**Comment by ml019** [comment]
Drafted a PR reflecting changes above. Seems a pretty straight forward change but needs discussion of impact on UI.
