### ISSUE TITLE
[BUG] Stack trace when fetching open api specification

### ISSUE THREAD

**Issue by ml019** [hamlet-io/executor-python#295]
## Current Behaviour
```
(Warn) Skipping login to AWS this won't allow you to access AWS but will continue
Traceback (most recent call last):
  File "/usr/bin/aws", line 19, in <module>
    import awscli.clidriver
  File "/usr/lib/python3/dist-packages/awscli/clidriver.py", line 36, in <module>
    from awscli.help import ProviderHelpCommand
  File "/usr/lib/python3/dist-packages/awscli/help.py", line 23, in <module>
    from botocore.docs.bcdoc import docevents
ImportError: cannot import name 'docevents' from 'botocore.docs.bcdoc' (/usr/local/lib/python3.8/dist-packages/botocore/docs/bcdoc/__init__.py)
```

## Expected Behaviour
Shouldn't get a stack track

## Steps to Reproduce
1. hamlet deploy create-deployments for an API unit
2.
3.
4.

## Your Environment
* hamlet 9.14.2
* local and unicycle (e0152eff) engines show the same behaviour

**Comment by roleyfoley** [comment]
Looks like this might be an issue with the awscli as outlined in https://github.com/boto/boto3/issues/2596 

I'd suggest updating your awscli installation which we don't manage as part of the hamlet python package installation.

**Comment by ml019** [comment]
I'll give that a try. Assume we keep this up to date in the devops container?

**Comment by ml019** [comment]
As suggested, upgrading awscli fixed the issue
```
pip install awscli --upgrade
```
