### ISSUE TITLE
[BUG] hamlet setup does not acknowledge ROOT_DIR under tram 25-feb-2022

### ISSUE THREAD

**Issue by ken9ross** [hamlet-io/executor-python#297]
## Current Behaviour
hamlet setup fails with "(Fatal) Can't locate the root of the directory tree"
Refer https://automation.alm.cp1.agriculture.gov.au/job/cotp-lae/job/manage-environment/16/console

## Expected Behaviour
Expected to behave the same as the train release 25-feb-2022
Refer https://automation.alm.cp1.agriculture.gov.au/job/cotp-lae/job/manage-environment/15/console

## Steps to Reproduce

1. New ken9ross_jenkins_update LAE manage-environment fails with HAMLET_ENGINE=tram
2. Change to HAMLET_ENGINE=train and it works

## Your Environment
* CMDB Version used: 
* Blueprint: 

Mike L suggested it may be executor-python and executor-bash getting out of sync with each other

**Comment by roleyfoley** [comment]
root dir seems to be working fine now and is in use across a number of pipelines and users.
