### ISSUE TITLE
[BUG]: code-tag parameter for hamlet release update-image-reference doesn't work

### ISSUE THREAD

**Issue by kshychko** [hamlet-io/executor-python#337]
## Current Behaviour

When I pass the `code-tag` parameter to `hamlet release update-image-reference` with a value that doesn't update the build.json file with the `Tag` property and provided value.
## Expected Behaviour

The build.json file is being updated with the value of the specified code-tag parameter.
## Possible Solution

Looks like [CODE_TAG](https://github.com/hamlet-io/executor-python/blob/master/hamlet/backend/automation/update_build_references/__init__.py#L19) isn't reaching the automation scripts, because enabled automation detailed debug produces the following output:
```
00:36:20  +(/home/jenkins/.hamlet/engine/engines/tram/hamlet-engine-base/executor-bash/automation/jenkins/aws/manageBuildReferences.sh:302): main(): (( INDEX=0 ))
00:36:20  +(/home/jenkins/.hamlet/engine/engines/tram/hamlet-engine-base/executor-bash/automation/jenkins/aws/manageBuildReferences.sh:302): main(): (( INDEX<1 ))
00:36:20  +(/home/jenkins/.hamlet/engine/engines/tram/hamlet-engine-base/executor-bash/automation/jenkins/aws/manageBuildReferences.sh:305): main(): CURRENT_DEPLOYMENT_UNIT=www-v1-web
00:36:20  +(/home/jenkins/.hamlet/engine/engines/tram/hamlet-engine-base/executor-bash/automation/jenkins/aws/manageBuildReferences.sh:306): main(): CODE_COMMIT=1789133d62d59ba6a60a394ef0d9b59b55198a4b
00:36:20  +(/home/jenkins/.hamlet/engine/engines/tram/hamlet-engine-base/executor-bash/automation/jenkins/aws/manageBuildReferences.sh:307): main(): CODE_TAG='?'
00:36:20  +(/home/jenkins/.hamlet/engine/engines/tram/hamlet-engine-base/executor-bash/automation/jenkins/aws/manageBuildReferences.sh:308): main(): CODE_REPO='?'
00:36:20  +(/home/jenkins/.hamlet/engine/engines/tram/hamlet-engine-base/executor-bash/automation/jenkins/aws/manageBuildReferences.sh:309): main(): CODE_PROVIDER=github
00:36:20  +(/home/jenkins/.hamlet/engine/engines/tram/hamlet-engine-base/executor-bash/automation/jenkins/aws/manageBuildReferences.sh:310): main(): IMAGE_FORMATS=docker
00:36:20  +(/home/jenkins/.hamlet/engine/engines/tram/hamlet-engine-base/executor-bash/automation/jenkins/aws/manageBuildReferences.sh:311): main(): REGISTRY_SCOPE='?'
```
## Steps to Reproduce

1. Pick any product migrated to a single Jenkins pipeline
2. Run a build for a tag
3. Replay (if needed) to add --code-tag parameter with a ${TAG_NAME} value
4. Check build.json file content.

## Your Environment
* CMDB Version used: v1.3.2
* Blueprint:

**Comment by ml019** [comment]
@kshychko I've just tested this with hamlet cli 9.22 and engine tram-20220802 and the code tag was correctly written to the repo.
Maybe try again with the latest builds? I'm happy to take a look with you to spot any differences.

**Comment by kshychko** [comment]
@ml019 , confirmed as fixed in the current tram release
