### ISSUE TITLE
hamlet generate patterns default to prompt

### ISSUE THREAD

**Issue by roleyfoley** [hamlet-io/executor-python#42]
Currently the cot generate command defaults to not prompting the user for input. Most of the cookie cutter templates require some user customisation to configure them properly so we should swap the default behaviour for user input to enabled rather than disabled

**Comment by RossMurr4y** [comment]
@roleyfoley I believe this one is now resolved?

**Comment by roleyfoley** [comment]
Yep the generation options are now at the root hamlet level instead of on the groups
