### ISSUE TITLE
Add Unitlist Support to Hamlet Create

### ISSUE THREAD

**Issue by RossMurr4y** [hamlet-io/executor-python#54]
## Description

Should be able to generate a unitlist from only `hamlet create template -l unitlist`

## Current Behavior

Have to call the shell script directly - `$GENERATION_DIR/createTemplate.sh -l unitlist`

**Comment by roleyfoley** [comment]
This has now been implemented using entrances 

`hamlet entrance invoke-entrance --entrance unitlist` 

@RossMurr4y  can you confirm this is working as expected

**Comment by RossMurr4y** [comment]
> This has now been implemented using entrances
> 
> `hamlet entrance invoke-entrance --entrance unitlist`
> 
> @RossMurr4y can you confirm this is working as expected

Yep, thats there now - I'm happy to call this closed.
