### ISSUE TITLE
QOL Features List

### ISSUE THREAD

**Issue by RossMurr4y** [hamlet-io/executor-python#58]
## Context
This ticket is to consolidate discussion for  "nice to have" and "quality of life" features for `executor-python` CLI. Such things are not necessarily enhancements are come down to user preference, so should be discussed first. Separate tickets can be made for any that are agreed upon.

**Comment by RossMurr4y** [comment]
I had a couple ideas and wanted to put them out there so started this ticket.


* Update `hamlet query describe ...` to default the `-I “”` and `-v “”`  so they are only required if they exist
* update `hamlet query list ...` options to match the way list items are hyphenated for entrances i.e `hamlet entrance list-entrances` for consistency across the CLI
* default `hamlet deploy` to perform `hamlet deploy run-deployments -r -g '.*' -u '.*'`.

**Comment by roleyfoley** [comment]
>     * [ ]   update `hamlet deploy` so that it can show deployments that it knows exist, but can't deploy yet because prerequisite deployments haven't happened. During a deployment of everything, it should identify that the prerequisites are now met and join the list of upcoming deployments. _This suggestion comes from noticing a difference between `hamlet query list components` and `hamlet deploy list-deployments` - both appear correct but it would be nice to be able to see all possible deployments if desired_

@RossMurr4y Is https://github.com/hamlet-io/executor-python/pull/94 enough to satisfy this?

**Comment by RossMurr4y** [comment]
Yep that meets the needs and intention of the original item. If I can see the options at any time without having yet deployed anything then we can call that one ticked off :)

**Comment by roleyfoley** [comment]
@RossMurr4y Is there anything else that we need to include in this ticket or Is it ready to close off?

**Comment by RossMurr4y** [comment]
Will close it off - a new ticket can be created for new needs.
