### ISSUE TITLE
azure deployments failing through hamlet deploy

### ISSUE THREAD

**Issue by ken9ross** [hamlet-io/executor-python#68]
Using hamlet deploy -p azure -f arm run-deployments -u baseline the manageDeployment.sh is not run. 

## Expected Behavior
When running `hamlet deploy -p azure -f arm run-deployments -u baseline` the completion stage of 
$GENERATION_DIR\manageDeployment.sh ...
Should be automatically run

## Current Behavior
Process halts after creating/updating the epilog scripts

## Possible Solution
I think this is because https://github.com/hamlet-io/executor-python/blob/master/hamlet-cli/hamlet/command/deploy/__init__.py needs from hamlet.backend.manage import deployment as manage_deployment_backend added at L10 and L255 to be a conditional
if generation.generation_provider == 'azure':
   manage_deployment_backend.run(**manage_args, _is_cli=True)
else:
   manage_stack_backend.run(**manage_args, _is_cli=True)
But it might be more sensible to collapse manageStack.sh and manageDeployment.sh, or create a consolidated entry point script to route based on a mandatory provider flag (more easily extensible for future providers).

## Steps to Reproduce (for bugs)

1. Execute `hamlet deploy -p azure -f arm run-deployments -u baseline`

## Your Environment
* CMDB Version used: 
{
  "Version": {
    "Upgrade": "v1.3.2",
    "Cleanup": "v1.1.1"
  }
}
* Blueprint:

**Comment by roleyfoley** [comment]
@ken9ross Support for azure deployments was added as part of https://github.com/hamlet-io/executor-python/pull/71 

can you please test and confirm that it is working as expected

**Comment by ken9ross** [comment]
Blocked by https://github.com/hamlet-io/engine-plugin-azure/issues/222

**Comment by ken9ross** [comment]
Now working as expected
