### ISSUE TITLE
azure list occurrences missing information on deployed component

### ISSUE THREAD

**Issue by ken9ross** [hamlet-io/executor-python#70]
When using hamlet query list occurrences on an Azure provider, the InstanceId is not displayed for a deployed component. Since this is the method to determine whether not deployed or does not exist, this poses a problem

## Expected Behavior
An Instance Id should be displayed if the component is deployed (possibly Operation.serviceRequestId or Operation.Tracking Id)

**Improvement**: Add an additional column of Deployed to explicitly determine whether a component has been deployed or not, rather than relying on the implicit existence of an InstanceId 

## Current Behavior
hamlet query -r -p azure -f arm list occurrences displays an empty value for InstanceId

## Steps to Reproduce (for bugs)

1. On an Azure deployment
2. run hamlet query -r -p azure -f arm list occurrences on a deployed component

**Comment by roleyfoley** [comment]
So this is actually an issue in the engine itself, when the instance id is `default` the id field during processing is made to be empty. The same applies to any other reference to `default` in the layers ( Product, environment segment etc ) 

So I think we need to make some engine changes to include a RawId which we have for a couple of other Ids and use that when we refer to queries in hamlet.

**Comment by roleyfoley** [comment]
@ken9ross I think this has now been fixed as part of the deploy command 

can you have a look at the `hamlet deploy list-deployments` to see if that gives you want you were after

**Comment by ken9ross** [comment]
@roleyfoley Yes that addresses the critical issue of identifying deployed vs undeployed
