### ISSUE TITLE
Request - Throw on invalid "mode"

### ISSUE THREAD

**Issue by RossMurr4y** [hamlet-io/executor-python#83]
## Expected Behaviour

If I mistype a mode in a `hamlet deploy` argument, tell me so and do nothing.

## Current Behaviour

It will proceed as if the mode was unspecified, which may not be noticed immediately.

## Possible Solution

* query list of valid modes, validate against them and throw if one provided is not in the list. 

## Context

* I mistakenly thought that "whatif" was a mode, and it created templates as normal rather than provide me the potential changes.

**Comment by roleyfoley** [comment]
The deployment mode setup was a bit fun as they weren't explicitly defined orginally which meant that we didn't really know what modes were being used. 

So to work around that I added an _default mode which is used if a mode can't be found. So as it currently stands all modes are actually valid modes. If you disable this mode in a solution it should throw an error from the engine.

**Comment by roleyfoley** [comment]
We have identified the places where modes are currently used. Will now remove _default and throw an error if the mode can't be found
